name: Render Keep Alive

on:
  schedule:
    # Runs every 12 minutes, every day
    - cron: '*/12 * * * *'
  workflow_dispatch: # Lets you trigger it manually from GitHub

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: curl -I -s https://stockpro-backend-oa8i.onrender.com/ping
